name: Docker Image Build and Push to DockerHub

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Docker Hub Login
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build the docker image
      run: docker build -t quiz:latest .
    - name: Tag the image
      run: docker tag quiz:latest secrets.DOCKERHUB_USERNAME/quiz:latest
    - name: Push the image
      run: docker push secrets.DOCKERHUB_USERNAME/quiz:latest
